# Generated by Django 5.2.9 on 2025-12-11 14:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LaundryOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('service_type', models.CharField(choices=[('reguler', 'Reguler (2–3 hari)'), ('express', 'Express (1 hari)'), ('kilat', 'Kilat (6 jam)')], max_length=20)),
                ('pickup_time', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('request', 'Permintaan Masuk'), ('pickup', 'Dijemput Driver'), ('washing', 'Sedang Dicuci'), ('delivering', 'Sedang Diantar'), ('done', 'Selesai')], default='request', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laundry_orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
