# Generated by Django 5.2.9 on 2025-12-11 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='laundryorder',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='laundryorder',
            name='weight_kg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
